add ftp storage, add getFileMeta, setFileMeta functions
vedi/restifizer-files pull request #6
Opened 2017-04-25 16:17 UTC by egorpro123

2017-04-25 16:27 UTC, vedi requested changes

2017-04-25 16:27 UTC, vedi commented on storages/ftp.js
> +/* eslint-disable max-len */
remove it

2017-04-25 16:27 UTC, vedi commented on storages/ftp.js
> + * options:
it does not look like JSDoc. What a standard is it?

2017-04-25 16:27 UTC, vedi commented on storages/ftp.js
> +    let filename = fileMeta.filename;
camelCase it

2017-04-25 16:27 UTC, vedi commented on storages/ftp.js
> +    if (this.options.uploadPath) return path.join(this.options.uploadPath, fileName);
always add brackets `{}`, please

2017-04-25 16:27 UTC, vedi commented on storages/ftp.js
> +        return new Bb((resolve, reject) => {
`Bb.fromCallback` will look better

2017-04-26 04:32 UTC, egorpro123 commented on storages/ftp.js
> +/* eslint-disable max-len */
ok

2017-04-26 07:11 UTC, egorpro123 commented on storages/ftp.js
> + * options:
It just comment. Converted to JSDoc.

2017-04-26 07:15 UTC, egorpro123 commented on storages/ftp.js
> +    let filename = fileMeta.filename;
fixed

2017-04-26 07:45 UTC, egorpro123 commented on storages/ftp.js
> +    if (this.options.uploadPath) return path.join(this.options.uploadPath, fileName);
fixed

2017-04-26 08:14 UTC, egorpro123 commented on storages/ftp.js
> +        return new Bb((resolve, reject) => {
fixed

2017-04-26 09:34 UTC, vedi requested changes

2017-04-26 09:34 UTC, vedi commented on storages/ftp.js
> +    return this._connect()
```
return this
  ._connect()
  .then(() => Bb.fromCallback((callback) => {
    client.delete(this._fullRemoteFileName(fileMeta.fileName), callback);
  })
  .finally(() => {
    client.end();
  });
```

2017-04-26 10:06 UTC, egorpro123 commented on storages/ftp.js
> +    return this._connect()
Thanks. I will correct

2017-05-02 12:22 UTC, vedi requested changes

2017-05-02 12:22 UTC, vedi commented on storages/ftp.js
> +const Client = require('ftp');
no ftp in dependencies

2017-05-02 13:09 UTC, closed without merging

2017-05-02 13:09 UTC, vedi commented
pushed to `dev`